### ISSUE TITLE
Github Readme Stats 

### ISSUE THREAD

**Issue by anuraghazra** [technote-space/technote-space#6]
Hi @technote-space i'm Anurag. developer of [github-readme-stats](https://github.com/anuraghazra/github-readme-stats)

Currently github readme stats is facing some deployment issues and vercel is constantly blocking me & disabling the project, and i think the issue is that there are some user accounts which are causing vercel serverless function timeouts, and your username is also in the logs which i've seen, thats why i'm temporary blacklisting few usernames to test out the effect.
- Pull request: https://github.com/anuraghazra/github-readme-stats/pull/399

I hope you understand, meanwhile i would highly recommend you to deploy on your own vercel instance. https://github.com/anuraghazra/github-readme-stats/#deploy-on-your-own-vercel-instance

Thanks!

**Comment by technote-space** [comment]
@anuraghazra 
From the beginning, I was experiencing timeouts, so I used GitHub Actions to generat images once a day.
I'll try `Deploy on your own Vercel instance`.
Thank you.

P.S.
The variable `blacklist` should be named as `denylist`.
